spring:
  datasource:
    url: jdbc:postgresql://${APP_DB_URL:localhost}:${APP_DB_POTS:5432}/${APP_DB_NAME:meetfriends}
    username: ${APP_DB_USERNAME:postgres}
    password: ${APP_DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    openInView: false
    show-sql: true
    generate-ddl: true
  data:
    jpa:
      repositories.enabled: true

frontend:
  url: ${FRONTEND_API_URL:http://localhost:4200}